config/routes.rb
Certick::Application.routes.draw do

  resources :certifieds

  root 'sessions#new'
  resources :sessions, only: [:new, :create]
  get 'exit', to: 'sessions#logout', as: :logout

  
  
  resources :generate, only: [:create]
  get 'generate/:slug' => 'generate#new', :as => "generate_new"

  

end

app/models/certified.rb
class Certified < ActiveRecord::Base
	attr_accessor :event
	belongs_to :user

	validates :event_id, :name_color, :background_url, :presence => true

	store :events, accessors: [ :event_title, :event_start_at, :event_venue, :event_slug ]
	serialize :attendees, Hash
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :certifieds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # before_filter :charge_current_user, :except => [:logout]

  layout :layout

  def logout
    logger.info "logout - init"

    self.current_user = nil
    redirect_to root_path

    logger.info "logout - done"
  end

  def current_user
    session[:current_user_id]
  end

  def current_user=(user)
    session[:current_user_id] = user
  end

  protected
  def authenticate_user!
    redirect_to root_path unless current_user.token
  end

  def eventick
    Eventick::API.new
  end
  private
  def is_logged
    logger.info "check if user is logged."
    logger.info "redirect to certified index if user logged." if current_user and is_a? SessionsController
  end

  def layout
    # only turn it off for login pages:
    is_a?(SessionsController) || is_a?(GenerateController)  ? "welcome" : "application"
    # or turn layout off for every devise controller:
  end

  def require_login
  #   logger.info "check if controller need login."
  #
  #   if !is_a?(SessionsController) && !is_a?(GenerateController)
  #     logger.info "is not a sessions controler."
  #
  #     logger.info "redirect to root due to current user is nil." unless current_user
  #     redirect_to root_path unless current_user
  #   end
  #
  #   # redirect_to certifieds_path if current_user and is_a? SessionsController
  end

  # def charge_current_user
  #   @current_user = current_user
  # end
end

app/controllers/certifieds_controller.rb
class CertifiedsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_certified, only: [:show, :edit, :update, :destroy]

  respond_to :html

  # GET /certifieds
  # GET /certifieds.json
  def index
    @certifieds = Certified.where(user: self.current_user)
  end

  # GET /certifieds/1
  # GET /certifieds/1.json
  def show
  end

  # GET /certifieds/1/edit
  def edit
  end

  # GET /certifieds/new
  def new
    @certified = Certified.new(user: current_user)
    @events = Eventick::API.new.events(current_user.token).map { |p| [ p['title'], p['id'] ] }

    if @events.empty?
      flash.now[:notice] = "No events available to add abackground. All your events already have background set."
      redirect_to certifieds_url
    end
  end

  # POST /certifieds
  # POST /certifieds.json
  def create
    @certified = Certified.new(certified_params)
    @certified.events = events
    @certified.attendees = attendees
    @certified.slug = generate_token
    @certified.user = self.current_user

    flash[:notice] = "Certificado criado com sucesso." if @certified.save

    respond_with(@certified) do |format|
      format.html { redirect_to @certified }
    end
  end

  # PATCH/PUT /certifieds/1
  # PATCH/PUT /certifieds/1.json
  def update
    respond_to do |format|
      @certified.background_url = params[:background_url]

      if @certified.update(certified_params)
        format.html { redirect_to @certified, notice: 'Certified was successfully updated.' }
        format.json { head :no_content }
      else
        format.html {
          render action: 'edit', alert: @certified.errors.to_a
        }
        format.json { render json: @certified.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certifieds/1
  # DELETE /certifieds/1.json
  def destroy
    @certified.destroy
    respond_to do |format|
      format.html { redirect_to certifieds_url }
      format.json { head :no_content }
    end
  end

  private
  def events
    event = eventick.event(current_user.token, params[:certified][:event_id]).first
    { event_title: event['title'], event_start_at: event['start_at'], event_venue: event['venue'], event_slug: event['slug'] }
  end

  def attendees
    hash = { }
    attendees = eventick.attendees(current_user.token, params[:certified][:event_id])
    attendees.each { |a| hash[a['email']] = a['name'] }
    hash
  end

  def generate_token
    token = loop do
      random_token = SecureRandom.urlsafe_base64(nil, false)
      break random_token unless Certified.where(slug: random_token).exists?
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_certified
    @certified = Certified.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def certified_params
    params.require(:certified).permit( :background_url, :event_id, :name_color)
  end
end

app/controllers/generate_controller.rb
class GenerateController < ApplicationController
	before_action :set_certified, only: [:new, :create, :show]


	# GET /generate/1
  # GET /generate/1.json
  def new
  	@certified
  end

  # POST /generate
  # POST /generate.json
  def create
    attendee = @certified.attendees[params[:email]]

    if attendee
			@name = attendee.upcase
      render 'result', layout: false
    elsif
      redirect_to generate_new_url(params), notice: 'Seu email não foi localizado, por favor utilize o mesmo email utilizado no Eventick.'
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_certified
    @certified = Certified.where(slug: params[:slug]).first
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def certified_params
    params.require(:certified).permit(:slug, :background)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
	end

	def create
		token = authenticate(params[:email], params[:password])

		if token
			self.current_user = User.find_or_create_by(token: token)
			redirect_to certifieds_path, notice: 'Bem vindo!'
		else
			flash.now[:alert] = 'Usuário ou senha inválida.'
			render :new
		end
	end

	private
	def authenticate(email, password)
		Eventick::API.new.token(email, password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def slug_full_url slug
		root_url + "generate/#{slug}"
	end
end

module ActionController
  module Flash

    def render(*args)
      options = args.last.is_a?(Hash) ? args.last : {}

      if alert = options.delete(:alert)
        flash[:alert] = alert
      end

      if notice = options.delete(:notice)
        flash[:notice] = notice
      end

      if other = options.delete(:flash)
        flash.update(other)
      end

      super(*args)
    end

  end
end

app/helpers/certifieds_helper.rb
module CertifiedsHelper
	protected
    def generate_token
      token = loop do
        random_token = SecureRandom.urlsafe_base64(nil, false)
        break random_token unless Certified.where(slug: random_token).exists?
      end
    end
end

app/views/certifieds/_form.html.erb
<%= form_for @certified, html: { role: 'form', multipart: true } do |f| %>
  <div class="from-group">
    <%= f.label :event %>
    <% if edit %>
      <%= @certified.event.title %>
    <% else %>
      <%= f.select :event_id, @events, { include_blank: true }, { class: 'form-control'} %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :background_url  %>
    <br/>
    <%= f.hidden_field :background_url, role: "uploadcare-uploader", 'data-preview-step' => "false", 'data-images-only' => "true", 'data-crop'=> "1024x768 minimum", 'data-clearable' => "true",  class: 'form-control' %>

  </div>
  <div class="form-group">
    <%= f.label :name_color  %>

    <%= f.text_field :name_color, class: 'form-control color', style: "width:100px;"  %>

  </div>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t(:cancel, :default => t("helpers.links.cancel")), certifieds_path, class: 'btn btn-danger' %>
<% end %>


<h2>Template da imagem</h2>
<%= image_tag("templates/certick_template_background_001.png") %>

app/views/certifieds/edit.html.erb
<%- model_class = Certified -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form', :locals => { :edit => true }%>

app/views/certifieds/index.html.erb
<% model_class = Certified %>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:event) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:thumb) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @certifieds.each do |certified| %>
      <tr>
        <td><%= link_to certified.event.title, certified_path(certified) %></td>
        <td><%= slug_full_url(certified.slug) %><%= link_to image_tag(image_path "out_16x16.png"), slug_full_url(certified.slug) , :class => 'out', target: "_blank" %></td>

        <td><%= image_tag certified.background_url.resize(:thumb) %></td>
        <td>

          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      certified_path(certified),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Novo', new_certified_path, class: 'btn btn-primary' %>

app/views/certifieds/new.html.erb
<% model_class = Certified %>
<div class="page-header">
  <h1><%= t '.title', :default => [:'helpers.titles.new', "Novo %{model}"], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form', locals: { edit: false }  %>

app/views/certifieds/show.html.erb
<%- model_class = Certified -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %> do <%= @certified.event_title %></h1>
</div>

<div class="well clip" >
  <span id="slug_span"><%= slug_full_url(@certified.slug) %></span>
</div>

<button id='clip_button' class='btn show' data-clipboard-target='slug_span' title='Click me to copy to clipboard.'>
    <%= image_tag image_path "copy_32x32.png" %>
</button>

<a href="<%= slug_full_url(@certified.slug) %>" target="_blank">
  <button class='btn show' title='Go to public url.'>
    <%= image_tag image_path "out_32x32.png" %>
  </button>
</a>

<div class="clear"></div>

<div class="control-group">
	Preview:
</div>

<div class="well" style="float:left;">
  <%= image_tag @certified.background_url.resize(:large)  %>
</div>

<div class="clear"></div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              certifieds_path, :class => 'btn'  %>

</div>

<script>
  $(document).ready(function() {
    var clip = new ZeroClipboard($("#clip_button"))
  });
</script>

app/views/generate/_form.html.erb
<%= form_tag '/generate', :method => :post do %>
  <%= hidden_field_tag :slug, @certified.slug %>
  <div class="form-group" >
    <h2>Seu certificado está aguardando você!</h2>
    <h5>Digite seu email cadastrado no eventick e clique em gerar certificado.</h5>
  </div>
  <br/>

  <div class="form-group">
    <%= label_tag :email %>
    <%= text_field_tag :email, nil, :class => 'form-control'%>
  </div>

  <%= submit_tag 'Gerar Certificado', :class => 'btn btn-primary'%>
<% end %>

app/views/generate/new.html.erb
<% model_class = Certified %>
<div class="container">
  <div class="row">
    <div class="page-header">
      <h1><%=t '.title', :default => [:'helpers.titles.new', "#{@certified.event.title}"], :model => model_class.model_name.human.titleize %></h1>
    </div>
    <%= render :partial => 'form' %>
  </div>
</div>

app/views/generate/result.html.erb
<style>
  body {
    margin: 0;
  }

  h1, h2, span, p {
    position: absolute;
    margin-left: auto;
    margin-right: auto;
    left: 0;
    right: 0;
    height: 50px;
  }

  h1{
    font-size: 40pt;
    top: 100px;
  }

  .name {
    font-size: 20pt;
    top: 445px;
    font-family: verdana;
  }

  h2{
    font-size: 25pt;
    top: 250px;
  }

  p{
    font-size: 25pt;
    top: 550px;
    width: 50%
  }

  .well{
    margin: 20px;
    min-height:20px;
    padding:9px;
    background-color:#f5f5f5;
    border:1px solid #e3e3e3;
    -webkit-border-radius:4px;
    -moz-border-radius:4px;
    border-radius:4px;
    -webkit-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.05);
    -moz-box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.05);
    box-shadow:inset 0 1px 1px rgba(0, 0, 0, 0.05);
    width: 1024px;
  }
  .well blockquote{border-color:#ddd;border-color:rgba(0, 0, 0, 0.15);}
</style>

<center>
  <div class="well">
    <!-- <h1 class="header"> CERTIFICADO </h1> -->
    <!-- <h2> Certificamos que </h2> -->
    <span class="name" style="color: <%= @certified.name_color %>"><%= @name %></span>

    <%= image_tag @certified.background_url, :class => 'image', style: "height: 768px; width:1024px" %>

    <!-- <p> Participou do evento Front in BH, no Teatro Ney Soares, na cidade de Belo Horizonte / MG, no dia
    26 de julho de 2014, com duração de 10 horas. </p> -->

  </div>
<center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Certick" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    


    <%= javascript_include_tag "application" %>


  </head>
  <body>

  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Certick</a>
        </div>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "Meus certificados", certifieds_path %></li>
        </ul>


        <ul class="nav navbar-nav navbar-right">
          <li class='navbar-text'> User: <%= @current_user.email%></li>
          <li><%= link_to "Logout", logout_path  %></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <%= bootstrap_flash %>
      <%= yield %>
    </div><!--/row-->
  </div> <!-- /container -->

  <div class="footer">
    <div class="container">
      <p class="text-muted">By Gustavo Porpino</p>
    </div>
  </div>

  </body>
  <script>
    UPLOADCARE_LOCALE = "en";
    UPLOADCARE_TABS = "file url facebook gdrive box skydrive instagram evernote";
    UPLOADCARE_AUTOSTORE = true;
    UPLOADCARE_PUBLIC_KEY = "1ea1fd70045cacc6ef90";
  </script>
  <script src="//ucarecdn.com/widget/1.3.1/uploadcare/uploadcare-1.3.1.min.js"></script>
  <script>
    $(document).ready(function () {

      var updatePreview = function() {
          var color = $(this).chromoselector('getColor');
          $(this).css({
              'background-color': color.getHexString(),
              'color': color.getTextColor().getHexString(),
              'text-shadow': '0 1px 0 ' + color.getTextColor().getTextColor().getHexString()
          });
      };

      $('.color').chromoselector({
        create:updatePreview,
        update: updatePreview
      });

      $('.color').val('#000000')
    });
  </script>
</html>

app/views/layouts/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Certick" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <a class="navbar-brand" href="#">Certick</a>
        </div>
      </div>
    </nav>

    <%= bootstrap_flash %>
    <%= yield %>

  </body>
</html>